### ISSUE TITLE
If person A is sending chat to person B and again person A opens the chat from the chatscreen then a new document is automatically created in the firestore and the previous chats are not showing up. Also the ListTile from the chatscreen is not showing up.

### ISSUE THREAD

**Issue by SamwitAdhikary** [fpatelm/Cupertino-Chat-App#1]

**Comment by SamwitAdhikary** [comment]
E/flutter (29035): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element

This error is showing in the debug console.

**Comment by fpatelm** [comment]
Hello @SamwitAdhikary, can you tell me the steps to reproduce the error? Tell me as well if you used firebase emulator/cloud, and phone emulator/real devices?

**Comment by SamwitAdhikary** [comment]
I am using firebase cloud. Both Android emulator and on real devices the error is happening.

Steps that throws error in my case:

Step 1 - When the chat screen is clear as no conversation happened, Person A sends a message to Person B from the peoples screen.

Step 2 - Now the chat screen is populated showing the Person name and the message. If person B is not replying and Person A opens the chat of Person B from the chat screen then the error occurs. If person B opens the chat and reply to Person A and at that time Person A opens the chat there is no error.

**Comment by fpatelm** [comment]
@SamwitAdhikary would you be willing to collaborate to this repository to provide the fix and open a pull request?

**Comment by SamwitAdhikary** [comment]
I tried very much but didn't get the solution. I am not understanding why it is always creating a new document in the firestore when the person is not replying and I opend the chat of that person. When opening the chat from the people screen everything is fine but is creates error when opening the chat from the chat screen.

**Comment by fpatelm** [comment]
@SamwitAdhikary I will check that and update this thread with my findings/solutions.

**Comment by SamwitAdhikary** [comment]
Please sir complete this series as fast as possible. I am following your tutorial and this is my college project.

**Comment by Usamamajid13** [comment]
I have an issue. I am sending the data on the firebase messages thing and messages are stored in firebase but it is not displaying on the screen. No error is coming and also no messages are displaying. Can you please help me with this?

**Comment by leozap00** [comment]
This issue is fixed? On firestore I've found that is passing only the friendName and friendUid

**Comment by Samialturk** [comment]
I fixed it  check the closed issues

**Comment by fpatelm** [comment]
I implemented a better approach with records auto-created in firestore using firebase function, the solution is described here: https://www.youtube.com/watch?v=tnnUBEpELy8
@Samialturk  thanks you for the fix, would you please open a PR of your fix so that I merge it to the main branch?
