### ISSUE TITLE
calling chat detail screen from chats page 

### ISSUE THREAD

**Issue by Samialturk** [fpatelm/Cupertino-Chat-App#6]
The issue is that when the last message is sent, it stores the sender uid, so if the sender goes back to chats screens then wants to send another msg and clicks on the chat to call chat detail screen, it calls using the friendUid which is his own uid (cz it is stored in the lastmsg). so it will create a new doc on firebase where the sender and the receiver are the same

**Comment by Samialturk** [comment]
I was able to solve this issue, if you want to mention it in the comments on Youtube and modify it in your code:

1- when Sending a message in chat detail screen (instead of saving just one uid with the msg and createdOn in Firebasse, i saved both Uids ; the sender and reciever)


  void sendMessage(String msg) {
    if (msg == '') return;

    chats.doc(chatDocId).collection('messages').add({
      'createdOn': FieldValue.serverTimestamp(),
      'oneUid': currentUserId,
      'twoUid': bloggerUid,
      'friendName': friendName,
      'msg': msg,
    }).then((value) {
      _messageTextController.text = '';
    });
  }



2- in the chat page, when clicking on the chat, i added an if statement, 

var cUser = FirebaseAuth.instance.currentUser?.uid,
onTap: () => {
                             
                                if (cUser == snap['oneUid'])
                                  {
                                    sendMsg(context, snap['friendName'],
                                        snap['twoUid']),
                                  
                                  }
                                else
                                  {
                                    sendMsg(context, snap['friendName'],snap['oneUid'])
                               
                                  }
                              }

**Comment by Samialturk** [comment]
I have another issue that ive been trying to solve for 2 days,
if you can please help me ,
thanks

**Comment by fpatelm** [comment]
Hello @Samialturk I created a better solution for the chat message using firebase functions, the solution is described here: https://www.youtube.com/watch?v=tnnUBEpELy8
